version: '3.9'
services:
  dnsmasq:
    container_name: dnsmasq
    image: ghcr.io/chrisanderton/docker-dnsmasq:v2.90-r3
    
    volumes:
      - hosts:/etc/host:ro

    command:
      - --hostsdir=/etc/host
      - --log-queries
      - --interface=*
      - --log-facility=-
      - --server=1.1.1.1

    network_mode: service:tailscale
    
    depends_on:
      - tailscale

  cron:
    container_name: cron
    image: ghcr.io/chrisanderton/docker-crond:v3.20.0
    restart: unless-stopped
    
    volumes:
      - ./cron/vaultwarden-backup.sh:/etc/periodic/daily/vaultwarden-backup:ro
      - vaultwarden-data:/vaultwarden/data:ro
      - backup-data:/backup

    env_file:
      - ./.env.aws
      - ./.env.host
      - ./.env.backup
      
    networks:
      - cron

  caddy:
    container_name: caddy
    image: ghcr.io/chrisanderton/docker-caddy-cloudflare-ddns:v2.7.6
    restart: unless-stopped

    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro

    env_file:
      - ./.env.email
      - ./.env.cloudflare
      - ./.env.host

    hostname: "caddy.dc"
    ports:
      - 443:443
    networks: 
      - caddy

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:1.30.1
    restart: unless-stopped

    volumes:
      - vaultwarden-data:/data

    env_file:
      - ./.env.email
      - ./.env.host
      - ./.env.vaultwarden

    hostname: "vaultwarden.dc"
    networks:
      - caddy

  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:v1.56.1
    restart: unless-stopped
    
    volumes:
      - tailscale-data:/var/lib
      - ./tailscale/tailscale.sh:/usr/bin/tailscale:ro
      - hosts:/etc/host

    env_file:
      - ./.env.host
      - ./.env.tailscale

    entrypoint: /usr/bin/tailscale

    network_mode: service:caddy

    depends_on:
      - caddy
    
networks:
  cron:
  caddy:
volumes:
  tailscale-data:
  caddy-data:
  caddy-config:
  vaultwarden-data:
  hosts:
  backup-data:
